(function(){
  'use strict';
  window.KetimeBuptUI={mount:function(bridge){
    var previousFocus=null,preview=null,busy=false,request=null;
    var box=document.createElement('div');box.className='overlay';box.id='bupt-overlay';
    box.innerHTML='<section class="modal bupt-modal" role="dialog" aria-modal="true" aria-labelledby="bupt-title"><h2 class="modal-title" id="bupt-title">北邮课表同步</h2><p class="bupt-note">只读取当前学期课表。账号密码仅在本机内存中使用，经 HTTPS 直连学校；不上传 GitHub、不写入本地存储。此版不包含教务云作业同步。</p><div id="bupt-local-hint" class="link-summary" hidden>同步需通过本地服务打开。请双击文件夹中的 start-ketime.cmd，再访问 <a href="http://127.0.0.1:8766/" target="_blank" rel="noopener">本机刻时</a>。原文件页面与本机服务的存储独立，请先在下方导出备份，再在新页面恢复。</div><form id="bupt-form"><div class="form-row"><label class="form-group"><span class="form-label">教务账号</span><input id="bupt-account" class="form-input" autocomplete="username" maxlength="32" required></label><label class="form-group"><span class="form-label">教务密码（非教务云）</span><input id="bupt-password" type="password" class="form-input" autocomplete="off" maxlength="256" required></label></div><label class="form-group" style="display:block"><span class="form-label">第一教学周周一（通常自动识别；缺失时填写）</span><input id="bupt-term-start" type="date" class="form-input"></label><button type="submit" class="btn btn-primary" id="bupt-fetch">获取课表并预览</button></form><p id="bupt-status" role="status" aria-live="polite" class="bupt-status"></p><div id="bupt-preview" hidden><p id="bupt-summary"></p><p id="bupt-warnings" class="bupt-note"></p><label class="check-line"><input type="checkbox" id="bupt-remove">移除学校已取消的课程（保留已完成、关联项目或手动编辑的日程）</label><div class="bupt-course-scroll"><table class="bupt-course-table"><thead><tr><th>课程</th><th>上课安排</th><th>教师 / 地点</th></tr></thead><tbody id="bupt-courses"></tbody></table></div><p class="bupt-note">按实际教学周和单双周展开到日期。新增课程默认不关联项目；导入后可以自行关联。重复同步保留完成状态、颜色和项目关联，手动编辑的名称、日期、时间不覆盖。</p><button id="bupt-import" class="btn btn-primary" type="button">确认导入日程表</button></div><details class="bupt-backup"><summary>本地数据备份 / 恢复</summary><p class="bupt-note">备份包括全部项目、日程、待收纳与成长曲线，不含账号密码。恢复会替换当前页面的数据，建议先导出。</p><button id="bupt-export" type="button" class="btn">导出当前数据</button> <button id="bupt-restore" type="button" class="btn">恢复备份</button><input type="file" id="bupt-backup-file" accept=".json,application/json" hidden></details><div class="modal-actions"><button id="bupt-close" class="btn" type="button">关闭</button></div></section>';
    document.body.appendChild(box);var $=function(id){return document.getElementById(id)};
    function status(message,error){$('bupt-status').textContent=message;$('bupt-status').classList.toggle('error',!!error)}
    function enable(){busy=false;$('bupt-fetch').disabled=!localService();$('bupt-import').disabled=false}
    function localService(){return location.protocol==='http:'&&location.hostname==='127.0.0.1'}
    function close(){if(request)request.abort();request=null;preview=null;$('bupt-password').value='';$('bupt-account').value='';$('bupt-preview').hidden=true;box.classList.remove('visible');enable();if(previousFocus)previousFocus.focus()}
    function summary(){if(!preview)return;var p=window.KetimeBupt.plan(bridge.getState().schedules,preview,{removeMissing:$('bupt-remove').checked});$('bupt-summary').textContent=preview.termId+' 学期 · 第一周 '+preview.termStart+' · '+preview.events.length+' 次课程；新增 '+p.added+'，更新 '+p.updated+'，不变 '+p.unchanged+'，保留手动编辑 '+p.keptEdits+'，取消 '+p.cancelled+'，移除 '+p.removed+'。';return p}
    $('bupt-sync-btn').addEventListener('click',function(){previousFocus=document.activeElement;box.classList.add('visible');$('bupt-local-hint').hidden=localService();$('bupt-fetch').disabled=!localService();status('');(localService()?$('bupt-account'):$('bupt-export')).focus()});
    $('bupt-close').addEventListener('click',close);box.addEventListener('click',function(e){if(e.target===box)close()});box.addEventListener('keydown',function(e){if(e.key==='Escape'){e.stopPropagation();close()}if(e.key==='Tab'){var nodes=Array.from(box.querySelectorAll('button,input,a,summary')).filter(function(n){return !n.disabled&&n.getClientRects().length&&!n.hidden}),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
    $('bupt-remove').addEventListener('change',function(){try{summary()}catch(e){status(e.message,true)}});
    $('bupt-form').addEventListener('submit',async function(e){
      e.preventDefault();if(busy||!localService())return;busy=true;preview=null;$('bupt-preview').hidden=true;$('bupt-fetch').disabled=true;status('正在连接北邮教务并获取当前学期课表…');request=new AbortController();var abort=request,timeout=setTimeout(function(){abort.abort()},90000);
      try{
        var configResponse=await fetch('/api/config',{cache:'no-store',signal:abort.signal});if(!configResponse.ok)throw Error('本地服务不可用，请重新启动。');var config=await configResponse.json();
        var body=JSON.stringify({account:$('bupt-account').value.trim(),password:$('bupt-password').value,termStart:$('bupt-term-start').value});$('bupt-password').value='';
        var response=await fetch('/api/bupt/timetable',{method:'POST',headers:{'Content-Type':'application/json','X-Ketime-Token':config.csrfToken},body:body,cache:'no-store',signal:abort.signal});body=null;var result=await response.json();if(!response.ok)throw Error(result.error||'学校课表获取失败。');window.KetimeBupt.validate(result);if(request!==abort)return;preview=result;
        $('bupt-remove').checked=false;$('bupt-remove').disabled=!result.complete;summary();$('bupt-warnings').textContent=(result.warnings||[]).join(' ');$('bupt-courses').replaceChildren();
        result.courses.forEach(function(course){var row=document.createElement('tr');[course.name,'周'+['','一','二','三','四','五','六','日'][course.weekday]+' '+course.start+'–'+course.end+' / '+course.weeks.join(',')+' 周',[course.teacher,course.location].filter(Boolean).join(' / ')].forEach(function(text){var cell=document.createElement('td');cell.textContent=text;row.appendChild(cell)});$('bupt-courses').appendChild(row)});
        $('bupt-preview').hidden=false;status(result.events.length?'课表已获取，请核对第一周日期及课程后确认导入。':'本学期暂未返回课程，请核对后再确认。');
      }catch(error){if(request===abort)status(error.name==='AbortError'?'获取已取消或超时，请稍后重试。':error.message,true)}finally{clearTimeout(timeout);$('bupt-password').value='';if(request===abort){request=null;enable()}}
    });
    $('bupt-import').addEventListener('click',function(){if(busy||!preview)return;try{var old=bridge.getState().buptSync;if(old&&old.accountKey&&old.accountKey!==preview.accountKey&&!confirm('本次账号与上次不同；课程将作为另一账号的课表添加，旧账号课程不会删除。继续？'))return;var p=summary();if(p.removed&&!confirm('确认移除 '+p.removed+' 项学校已取消、且未完成及未手动编辑的课程？'))return;bridge.apply(p);status('导入成功：新增 '+p.added+' 次课程，更新 '+p.updated+' 次。数据已保存在本机。');preview=null;$('bupt-preview').hidden=true;$('bupt-account').value=''}catch(e){status(e.message,true)}});
    $('bupt-export').addEventListener('click',function(){var blob=new Blob([JSON.stringify(bridge.getState(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ketime-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(url)},1000)});
    $('bupt-restore').addEventListener('click',function(){if(!busy)$('bupt-backup-file').click()});
    $('bupt-backup-file').addEventListener('change',async function(){var file=this.files[0];this.value='';if(!file)return;try{if(file.size>10*1024*1024)throw Error('备份文件过大。');var data=JSON.parse(await file.text());if(!data||!Array.isArray(data.projects)||!Array.isArray(data.schedules)||!Array.isArray(data.inbox||data.todos)||!data.growth||!Array.isArray(data.growth.series))throw Error('这不是完整的刻时备份文件。');if(confirm('恢复将替换当前页面的全部数据。确认已导出当前备份并继续？')){bridge.restore(data);preview=null;$('bupt-preview').hidden=true;status('备份已恢复。')}}catch(e){status('恢复失败：'+e.message,true)}});
  }};
})();
