(function(){
  'use strict';
  window.KetimeBuptUI={mount:function(bridge){
    var $=function(id){return document.getElementById(id)},previousFocus=null,saving=false,importing=false;
    var box=document.createElement('div');box.className='overlay';box.id='settings-overlay';
    box.innerHTML='<section class="modal" role="dialog" aria-modal="true" aria-labelledby="settings-title"><h2 id="settings-title" class="modal-title">设置</h2><p class="bupt-note">账号及两种密码永久保存在本机 Windows 用户级加密文件中。不会放入浏览器存储、备份文件或 GitHub。通常只能由原 Windows 用户在原电脑使用；同一用户权限下的其他程序仍可能读取，请保护电脑账号。</p><p id="settings-local-hint" class="link-summary" hidden>账号保存及同步需通过本机服务打开。请双击 start-ketime.cmd 后访问 <a href="http://127.0.0.1:8766/" target="_blank" rel="noopener">本机刻时</a>。原 HTML 与本机服务存储独立，请先导出数据，再在新页面恢复。</p><form id="settings-form"><label class="form-group" style="display:block"><span class="form-label">账号 / 学号</span><input id="settings-account" class="form-input" autocomplete="username" maxlength="32" required></label><div class="form-row"><label class="form-group"><span class="form-label">教务密码</span><input id="settings-password" type="password" class="form-input" autocomplete="off" maxlength="256"></label><label class="form-group"><span class="form-label">教学云 / 统一认证密码</span><input id="settings-cloud-password" type="password" class="form-input" autocomplete="off" maxlength="256"></label></div><p class="bupt-note">首次保存或更换账号时填写两种密码；账号不变时，密码留空表示保留原值。</p><label class="form-group" style="display:block"><span class="form-label">第一教学周周一（通常自动识别，缺失时填写）</span><input id="settings-term-start" type="date" class="form-input"></label><button id="settings-save" type="submit" class="btn btn-primary">保存账号设置</button> <button id="settings-clear" type="button" class="btn btn-danger">清除已保存账号</button></form><p id="settings-status" class="bupt-status" role="status" aria-live="polite"></p><button id="settings-holidays" type="button" class="btn">节假日与调休设置</button><p class="bupt-note" style="margin-top:8px">节假日设置保存在当前页面本地数据中，刷新后保留，并随备份导出。</p><details class="bupt-backup"><summary>本地数据备份 / 恢复</summary><p class="bupt-note">含日程、今日提醒、项目、待收纳、成长曲线和节假日，不含账号密码。恢复会替换当前页面数据，请先备份。</p><button id="bupt-export" type="button" class="btn">导出当前数据</button> <button id="bupt-restore" type="button" class="btn">恢复备份</button><input id="bupt-backup-file" type="file" accept=".json,application/json" hidden></details><div class="modal-actions"><button id="settings-close" type="button" class="btn">关闭</button></div></section>';
    document.body.appendChild(box);
    function local(){return location.protocol==='http:'&&location.hostname==='127.0.0.1'}
    function status(text,error){$('settings-status').textContent=text;$('settings-status').classList.toggle('error',!!error)}
    function notify(text,error){var el=$('sync-status');if(el){el.textContent=text;el.classList.toggle('error',!!error)}}
    async function call(path,payload,signal){if(!local())throw Error('请通过 start-ketime.cmd 打开的本机页面使用账号保存和同步。');var response=await fetch('/api/config',{cache:'no-store',signal:signal});if(!response.ok)throw Error('本机服务不可用，请重新启动。');var config=await response.json(),version=String(config.version||'').split('.').map(Number);if(!(version[0]>0||version[0]===0&&version[1]>=5))throw Error('当前仍在运行旧版刻时服务，请重启 start-ketime.cmd 并刷新页面；账号密码尚未发送。');var result=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Ketime-Token':config.csrfToken},body:JSON.stringify(payload||{}),cache:'no-store',signal:signal});var data=await result.json();if(!result.ok){var error=Error(data.error||'本机服务请求失败。');error.code=data.code;throw error}return data}
    function pagePresentation(){return window.KetimeAndroid&&window.KetimeAndroid.settingsPage}
    function close(){box.classList.remove('visible');$('settings-password').value='';$('settings-cloud-password').value='';var page=pagePresentation();if(page)page.hide();else if(previousFocus)previousFocus.focus()}
    async function open(message){previousFocus=document.activeElement;var page=pagePresentation();if(page)page.show();box.classList.add('visible');$('settings-password').value='';$('settings-cloud-password').value='';$('settings-local-hint').hidden=local();$('settings-save').disabled=!local()||saving;$('settings-clear').disabled=!local()||saving;status(message||'正在读取本机设置…');if(!local()){status(message||'账号保存需通过本机服务使用。',true);if(!page)$('bupt-export').focus();return}try{var data=await call('/api/settings/read',{});if(!box.classList.contains('visible'))return;$('settings-account').value=data.account;$('settings-password').placeholder=data.hasPassword?'已保存；留空不更改':'请输入教务密码';$('settings-cloud-password').placeholder=data.hasCloudPassword?'已保存；留空不更改':'请输入教学云密码';$('settings-term-start').value=data.termStart||'';status(message||(data.account?'账号已在本机加密保存。':'尚未保存账号，请填写后保存。'));if(!page)$('settings-account').focus()}catch(e){status(e.message,true)}}
    window.KetimeAccount={call:call,read:function(signal){return call('/api/settings/read',{},signal)},open:open,close:close,notify:notify};
    $('settings-btn').addEventListener('click',function(){open()});$('settings-close').addEventListener('click',close);box.addEventListener('click',function(e){if(e.target===box&&!pagePresentation())close()});
    box.addEventListener('keydown',function(e){if(e.key==='Escape'){e.stopPropagation();close()}if(e.key==='Tab'&&!pagePresentation()){var nodes=Array.from(box.querySelectorAll('button,input,select,textarea,a,summary')).filter(function(n){return !n.disabled&&n.getClientRects().length}),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
    $('settings-form').addEventListener('submit',async function(e){e.preventDefault();if(saving)return;saving=true;$('settings-save').disabled=true;$('settings-clear').disabled=true;var payload={account:$('settings-account').value.trim(),password:$('settings-password').value,cloudPassword:$('settings-cloud-password').value,termStart:$('settings-term-start').value};$('settings-password').value='';$('settings-cloud-password').value='';try{var data=await call('/api/settings/save',payload);$('settings-password').placeholder=data.hasPassword?'已保存；留空不更改':'请输入教务密码';$('settings-cloud-password').placeholder=data.hasCloudPassword?'已保存；留空不更改':'请输入教学云密码';status('已在本机加密保存。现在可直接点击导入课表或导入作业。')}catch(error){status(error.message,true)}finally{payload.password='';payload.cloudPassword='';saving=false;$('settings-save').disabled=false;$('settings-clear').disabled=false}});
    $('settings-clear').addEventListener('click',async function(){if(saving||!confirm('清除本机保存的账号及两种密码？日程、作业和节假日不会删除。'))return;saving=true;try{await call('/api/settings/save',{clear:true});$('settings-account').value='';$('settings-password').value='';$('settings-cloud-password').value='';$('settings-password').placeholder='请输入教务密码';$('settings-cloud-password').placeholder='请输入教学云密码';status('已清除本机保存的账号密码。')}catch(e){status(e.message,true)}finally{saving=false}});
    $('settings-holidays').addEventListener('click',function(){if(!pagePresentation())close();else{$('settings-password').value='';$('settings-cloud-password').value='';}$('holiday-btn').click()});
    $('bupt-sync-btn').addEventListener('click',async function(){if(importing)return;importing=true;var button=$('bupt-sync-btn'),controller=new AbortController(),timeout=setTimeout(function(){controller.abort()},90000);button.disabled=true;button.setAttribute('aria-busy','true');button.textContent='正在导入…';notify('正在获取课表…');try{var saved=await call('/api/settings/read',{},controller.signal);if(!saved.account||!saved.hasPassword){await open('请先保存账号和教务密码。');return}var data=await call('/api/bupt/timetable',{stored:true},controller.signal);window.KetimeBupt.validate(data);var plan=window.KetimeBupt.plan(bridge.getState().schedules,data,{removeMissing:false});bridge.apply(plan);notify('课表已更新：新增 '+plan.added+'，更新 '+plan.updated+'。'+(data.warnings||[]).join(' '))}catch(error){notify(error.name==='AbortError'?'课表导入超时，原数据未更改。':error.message,true);if(error.code==='SETTINGS_REQUIRED')open(error.message)}finally{clearTimeout(timeout);importing=false;button.disabled=false;button.removeAttribute('aria-busy');button.textContent='导入课表'}});
    $('bupt-export').addEventListener('click',function(){var json=JSON.stringify(bridge.getState(),null,2),name='ketime-backup-'+new Date().toISOString().slice(0,10)+'.json';if(window.KetimeAndroid&&window.KetimeAndroid.exportBackup){try{window.KetimeAndroid.exportBackup(json,name)}catch(e){status(e.message,true)}return}var blob=new Blob([json],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(function(){URL.revokeObjectURL(url)},1000)});
    $('bupt-restore').addEventListener('click',function(){$('bupt-backup-file').click()});
    $('bupt-backup-file').addEventListener('change',async function(){var file=this.files[0];this.value='';if(!file)return;try{if(file.size>10*1024*1024)throw Error('备份文件过大。');var data=JSON.parse(await file.text());if(!data||!Array.isArray(data.projects)||!Array.isArray(data.schedules)||!Array.isArray(data.inbox||data.todos)||!data.growth||!Array.isArray(data.growth.series))throw Error('这不是完整的刻时备份。');if(confirm('恢复将替换当前页面数据。确认已导出备份并继续？')){bridge.restore(data);status('备份已恢复；本机账号设置不受影响。')}}catch(e){status('恢复失败：'+e.message,true)}});
  }};
})();
