(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.KetimeSchool=api})(typeof window==='object'?window:globalThis,function(){
  'use strict';
  function clone(x){return JSON.parse(JSON.stringify(x))}
  function validDate(s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;var d=new Date(s+'T12:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===s}
  function normalizeRules(raw){return(Array.isArray(raw)?raw:[]).slice(0,200).map(function(r,i){return{id:String(r.id||'holiday_'+i),name:String(r.name||'假期').slice(0,80),enabled:Boolean(r.enabled),start:String(r.start||''),end:String(r.end||''),makeup:Boolean(r.makeup),moves:(Array.isArray(r.moves)?r.moves:[]).slice(0,100).map(function(m){return{from:String(m.from||''),to:String(m.to||'')}})}})}
  function validateRules(raw){var rules=normalizeRules(raw),active=rules.filter(function(r){return r.enabled}),sources=new Set(),targets=new Set();rules.forEach(function(r){if(!validDate(r.start)||!validDate(r.end)||r.start>r.end)throw Error('请为每个假期填写有效的起止日期（结束日期不早于开始日期）。');if((new Date(r.end)-new Date(r.start))/86400000>90)throw Error('单段假期不能超过 91 天。')});active.forEach(function(r,i){if(active.slice(i+1).some(function(q){return r.start<=q.end&&r.end>=q.start}))throw Error('启用的假期日期不能重叠。');if(r.makeup)r.moves.forEach(function(m){if(!validDate(m.from)||!validDate(m.to)||m.from<r.start||m.from>r.end||m.from===m.to)throw Error('调休原上课日期应位于对应假期内，补课日期必须有效且不同。');if(active.some(function(q){return m.to>=q.start&&m.to<=q.end}))throw Error('补课日期不能落在启用的放假区间内。');if(sources.has(m.from)||targets.has(m.to))throw Error('同一原上课日期或补课日期不能重复配置。');sources.add(m.from);targets.add(m.to)})});return rules}
  function decision(event,rules){if(!event||event.repeat!=='none'||!event.source||event.source.provider!=='bupt')return{hidden:false,date:event&&event.date,moved:false};var date=event.date;for(var i=0;i<(rules||[]).length;i++){var r=rules[i];if(!r.enabled||date<r.start||date>r.end)continue;var move=r.makeup&&(r.moves||[]).find(function(m){return m.from===date});return{hidden:!move,date:move?move.to:date,moved:!!move,holiday:r.name}}return{hidden:false,date:date,moved:false}}
  function impact(events,rules){var hidden=0,moved=0;(events||[]).forEach(function(e){var d=decision(e,rules);if(d.hidden)hidden++;if(d.moved)moved++});return{hidden:hidden,moved:moved}}
  function preset2026(){return[['元旦','2026-01-01','2026-01-03'],['春节','2026-02-15','2026-02-23'],['清明节','2026-04-04','2026-04-06'],['劳动节','2026-05-01','2026-05-05'],['端午节','2026-06-19','2026-06-21'],['中秋节','2026-09-25','2026-09-27'],['国庆节','2026-10-01','2026-10-07']].map(function(r,i){return{id:'holiday_2026_'+i,name:r[0],start:r[1],end:r[2],enabled:true,makeup:false,moves:[]}})}
  function normalizeHomeworkSource(s){if(!s||s.provider!=='bupt-ucloud'||!/^[a-f0-9]{24}$/.test(s.accountKey)||!/^[A-Za-z0-9_-]{1,160}$/.test(s.sourceId))return null;return{provider:'bupt-ucloud',accountKey:s.accountKey,sourceId:s.sourceId,title:String(s.title||'').slice(0,200),courseName:String(s.courseName||'').slice(0,200),dueAt:String(s.dueAt||'').slice(0,40),url:'https://ucloud.bupt.edu.cn/',snapshotName:String(s.snapshotName||'').slice(0,200)}}
  function normalizeHomeworkItem(item){var source=normalizeHomeworkSource(item&&item.source);if(!source||!source.title)return item;var name=((source.courseName?source.courseName+'：':'')+source.title).slice(0,200),legacy=((source.courseName?'【'+source.courseName+'】':'')+source.title).slice(0,200),unchanged=item.name===source.snapshotName||(!source.snapshotName&&item.name===legacy);source.snapshotName=name;return Object.assign({},item,{name:unchanged?name:item.name,source:source})}
  function normalizeHomeworkSync(s){return{seen:Array.from(new Set((Array.isArray(s&&s.seen)?s.seen:[]).filter(function(key){return typeof key==='string'&&/^[a-f0-9]{24}:[A-Za-z0-9_-]{1,160}$/.test(key)}))).slice(-50000),fetchedAt:String(s&&s.fetchedAt||'').slice(0,50)}}
  function homeworkPlan(existing,history,data,selected){if(!data||data.provider!=='bupt-ucloud'||!/^[a-f0-9]{24}$/.test(data.accountKey)||!Array.isArray(data.assignments)||data.assignments.length>10000)throw Error('作业列表格式不正确，未导入。');var ids=new Set();data.assignments.forEach(function(a){if(!a||!/^[A-Za-z0-9_-]{1,160}$/.test(a.sourceId)||ids.has(a.sourceId)||typeof a.name!=='string'||!a.name.trim()||a.name.length>200||typeof a.title!=='string'||typeof a.courseName!=='string'||typeof a.dueAt!=='string')throw Error('作业名称或编号异常，未导入。');ids.add(a.sourceId)});var inbox=clone(existing||[]),ledger=normalizeHomeworkSync(history),seen=new Set(ledger.seen),selection=selected?new Set(selected):null,added=0,updated=0,alreadyCollected=0,now=new Date().toISOString();data.assignments.forEach(function(a){if(selection&&!selection.has(a.sourceId))return;var key=data.accountKey+':'+a.sourceId,old=inbox.find(function(t){return t.source&&t.source.provider==='bupt-ucloud'&&t.source.accountKey===data.accountKey&&t.source.sourceId===a.sourceId}),metadata=normalizeHomeworkSource(Object.assign({},a,{provider:'bupt-ucloud',accountKey:data.accountKey,snapshotName:a.name}));if(old){var before=JSON.stringify(old);if(old.name===old.source.snapshotName)old.name=a.name;old.source=metadata;if(before!==JSON.stringify(old)){old.updatedAt=now;updated++}}else if(seen.has(key)){alreadyCollected++}else{var id='ucloud_'+data.accountKey+'_'+a.sourceId;if(inbox.some(function(t){return t.id===id}))throw Error('作业编号与本地事项冲突。');inbox.push({id:id,name:a.name,done:false,createdAt:now,updatedAt:now,source:metadata});added++}seen.add(key)});ledger.seen=Array.from(seen).slice(-50000);ledger.fetchedAt=String(data.fetchedAt||now);return{inbox:inbox,homeworkSync:ledger,added:added,updated:updated,alreadyCollected:alreadyCollected}}
  return{normalizeRules:normalizeRules,validateRules:validateRules,decision:decision,impact:impact,preset2026:preset2026,homeworkPlan:homeworkPlan,normalizeHomeworkSource:normalizeHomeworkSource,normalizeHomeworkItem:normalizeHomeworkItem,normalizeHomeworkSync:normalizeHomeworkSync};
});
