(function(){
  'use strict';
  window.KetimeSchoolUI={mount:function(bridge){
    var module=window.KetimeSchool,$=function(id){return document.getElementById(id)},rules=[],focusBefore=null,preview=null,loginId='',busy=false,abort=null;
    var holidayBox=document.createElement('div');holidayBox.className='overlay';holidayBox.id='holiday-overlay';
    holidayBox.innerHTML='<section class="modal school-modal" role="dialog" aria-modal="true" aria-labelledby="holiday-title"><h2 class="modal-title" id="holiday-title">节假日与调休</h2><p class="bupt-note">只作用于北邮同步导入的单次课程，不影响手动日程。假期内的课程从日程表移除，但保留原记录、勾选及关联，关闭规则即可恢复。学校调休安排需手动核对，不直接套用法定上班日。</p><button id="holiday-preset" type="button" class="btn">载入 2026 法定假期草案</button> <a class="bupt-note" href="https://www.wuhan.gov.cn/zwgk/tzgg/202609/t20260907_2844002.shtml" target="_blank" rel="noopener">日期来源</a><div id="holiday-rules"></div><button id="holiday-add" type="button" class="btn">＋ 自定义假期</button><p id="holiday-status" class="bupt-status" role="status" aria-live="polite"></p><div class="modal-actions"><button id="holiday-cancel" type="button" class="btn">取消</button><button id="holiday-save" type="button" class="btn btn-primary">保存并应用</button></div></section>';
    document.body.appendChild(holidayBox);
    function control(type,value,label,callback){var el=document.createElement('input');el.type=type;if(type==='checkbox')el.checked=!!value;else el.value=value||'';el.className=type==='checkbox'?'':'form-input';el.setAttribute('aria-label',label);el.addEventListener(type==='text'?'input':'change',function(){callback(type==='checkbox'?el.checked:el.value)});return el}
    function label(text,element){var el=document.createElement('label');el.className='school-field';var title=document.createElement('span');title.className='form-label';title.textContent=text;el.append(title,element);return el}
    function renderRules(){var list=$('holiday-rules');list.replaceChildren();rules.forEach(function(rule,index){var card=document.createElement('section');card.className='holiday-card';var top=document.createElement('div');top.className='school-row';top.append(label('启用',control('checkbox',rule.enabled,'启用 '+rule.name,function(v){rule.enabled=v})),label('节日名称',control('text',rule.name,'节日名称',function(v){rule.name=v})));var remove=document.createElement('button');remove.type='button';remove.className='btn btn-danger';remove.textContent='移除规则';remove.addEventListener('click',function(){rules.splice(index,1);renderRules()});top.append(remove);card.append(top);var dates=document.createElement('div');dates.className='form-row';dates.append(label('放假开始（含当天）',control('date',rule.start,'放假开始',function(v){rule.start=v})),label('放假结束（含当天）',control('date',rule.end,'放假结束',function(v){rule.end=v})));card.append(dates);card.append(label('有调休 / 补课',control('checkbox',rule.makeup,'有调休 '+rule.name,function(v){rule.makeup=v;renderRules()})));if(rule.makeup){var info=document.createElement('p');info.className='bupt-note';info.textContent='选择具体原上课日及补课日；未映射的假期课程仍停课。补课日原有课程保留，如有冲突请人工核对。';card.append(info);rule.moves.forEach(function(move,mi){var row=document.createElement('div');row.className='school-row';row.append(label('原上课日期',control('date',move.from,'原上课日期',function(v){move.from=v})),label('调至日期',control('date',move.to,'调至日期',function(v){move.to=v})));var del=document.createElement('button');del.type='button';del.className='btn';del.textContent='删除调休';del.addEventListener('click',function(){rule.moves.splice(mi,1);renderRules()});row.append(del);card.append(row)});var add=document.createElement('button');add.type='button';add.className='btn';add.textContent='＋ 添加调休日期';add.addEventListener('click',function(){rule.moves.push({from:rule.start,to:''});renderRules()});card.append(add)}list.append(card)});if(!rules.length){var empty=document.createElement('p');empty.className='bupt-note';empty.textContent='尚未设置假期。载入日期草案或自行添加，保存后生效。';list.append(empty)}}
    function holidayClose(){holidayBox.classList.remove('visible');if(focusBefore)focusBefore.focus()}
    $('holiday-btn').addEventListener('click',function(){focusBefore=document.activeElement;rules=module.normalizeRules(bridge.getState().holidays);renderRules();$('holiday-status').textContent='';holidayBox.classList.add('visible');$('holiday-preset').focus()});
    $('holiday-preset').addEventListener('click',function(){if(rules.length&&!confirm('替换当前编辑草案为 2026 法定假期？尚未保存的设置将被替换。'))return;rules=module.preset2026();renderRules()});
    $('holiday-add').addEventListener('click',function(){rules.push({id:'holiday_'+Date.now()+'_'+Math.random().toString(36).slice(2,7),name:'自定义假期',enabled:true,start:'',end:'',makeup:false,moves:[]});renderRules()});
    $('holiday-cancel').addEventListener('click',holidayClose);$('holiday-save').addEventListener('click',function(){try{var valid=module.validateRules(rules),impact=module.impact(bridge.getState().schedules,valid);if(!confirm('应用后 '+impact.hidden+' 次课程停课，'+impact.moved+' 次课程调休。原记录会保留，关闭规则可恢复。确认？'))return;bridge.saveHolidays(valid);holidayClose()}catch(e){$('holiday-status').textContent=e.message;$('holiday-status').classList.add('error')}});
    var cloudBox=document.createElement('div');cloudBox.className='overlay';cloudBox.id='ucloud-overlay';
    cloudBox.innerHTML='<section class="modal small" role="dialog" aria-modal="true" aria-labelledby="ucloud-title"><h2 class="modal-title" id="ucloud-title">教学云验证码</h2><p class="bupt-note">学校要求验证码，请填写后继续导入；无需再次输入账号密码。</p><form id="ucloud-form"><img id="ucloud-captcha-image" alt="统一认证验证码"><input id="ucloud-captcha" class="form-input" maxlength="32" autocomplete="off" aria-label="验证码" required><p id="ucloud-status" role="status" class="bupt-status" aria-live="polite"></p><button id="ucloud-fetch" class="btn btn-primary" type="submit">继续导入作业</button></form><div class="modal-actions"><button id="ucloud-close" type="button" class="btn">取消</button></div></section>';
    document.body.appendChild(cloudBox);
    function status(message,error){$('ucloud-status').textContent=message;$('ucloud-status').classList.toggle('error',!!error);window.KetimeAccount.notify(message,error)}
    function buttons(){$('ucloud-btn').disabled=busy;$('ucloud-btn').textContent=busy?'正在导入…':'导入作业';$('ucloud-btn').setAttribute('aria-busy',String(busy));$('ucloud-fetch').disabled=busy}
    function close(){if(abort)abort.abort();abort=null;busy=false;loginId='';$('ucloud-captcha').value='';$('ucloud-captcha-image').removeAttribute('src');cloudBox.classList.remove('visible');buttons();if(focusBefore)focusBefore.focus()}
    async function importAssignments(captcha,signal){var id=loginId;loginId='';var data=await window.KetimeAccount.call('/api/ucloud/homework',{stored:true,loginId:id,captcha:captcha||''},signal);if(signal.aborted)return;var state=bridge.getState(),plan=module.homeworkPlan(state.inbox,state.homeworkSync,data);bridge.applyHomework(plan);cloudBox.classList.remove('visible');$('ucloud-captcha').value='';$('ucloud-captcha-image').removeAttribute('src');status('作业已更新：新增 '+plan.added+'，更新 '+plan.updated+'，已收纳 / 删除跳过 '+plan.alreadyCollected+'。')}
    $('ucloud-btn').addEventListener('click',async function(){if(busy)return;focusBefore=document.activeElement;busy=true;buttons();abort=new AbortController();var current=abort,timeout=setTimeout(function(){current.abort()},180000);status('正在使用已保存账号读取教学云作业…');try{var settings=await window.KetimeAccount.read(current.signal);if(!settings.account||!settings.hasCloudPassword){await window.KetimeAccount.open('请先保存账号和教学云密码。');return}var prepared=await window.KetimeAccount.call('/api/ucloud/prepare',{},current.signal);loginId=prepared.loginId;if(prepared.captchaImage){$('ucloud-captcha-image').src=prepared.captchaImage;$('ucloud-captcha').value='';cloudBox.classList.add('visible');status('请填写学校验证码后继续导入。');$('ucloud-captcha').focus()}else await importAssignments('',current.signal)}catch(e){status(e.name==='AbortError'?'作业导入已取消或超时，原数据未更改。':e.message,true);if(e.code==='SETTINGS_REQUIRED')window.KetimeAccount.open(e.message)}finally{clearTimeout(timeout);if(abort===current){abort=null;busy=false;buttons()}}});
    $('ucloud-form').addEventListener('submit',async function(e){e.preventDefault();if(busy||!loginId)return;busy=true;buttons();abort=new AbortController();var current=abort,timeout=setTimeout(function(){current.abort()},180000);try{await importAssignments($('ucloud-captcha').value.trim(),current.signal)}catch(error){status(error.name==='AbortError'?'作业导入已取消或超时。':error.message+'；如需重试，请取消后再次点击导入作业。',true)}finally{clearTimeout(timeout);if(abort===current){abort=null;busy=false;buttons()}}});
    $('ucloud-close').addEventListener('click',close);
    [holidayBox,cloudBox].forEach(function(box){box.addEventListener('click',function(e){if(e.target===box)(box===holidayBox?holidayClose:close)()});box.addEventListener('keydown',function(e){if(e.key==='Escape'){e.stopPropagation();(box===holidayBox?holidayClose:close)()}if(e.key==='Tab'){var all=Array.from(box.querySelectorAll('button,input,a')).filter(function(n){return !n.disabled&&n.getClientRects().length}),first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}})});
  }};
})();
