const test=require('node:test');
const assert=require('node:assert/strict');
const {plan,validate}=require('../bupt-import');
function fixture(){return{provider:'bupt',accountKey:'a'.repeat(24),termId:'2026-2027-1',termStart:'2026-08-31',complete:true,courses:[],fetchedAt:'2026-10-02T00:00:00+08:00',events:[{sourceId:'b'.repeat(32),courseId:'test-course',name:'测试课程',date:'2026-10-05',start:'08:00',end:'09:35',teacher:'测试教师',location:'教学楼101',week:6,sections:'1-2'}]}}
test('first import and repeat import are idempotent',()=>{const data=fixture(),a=plan([],data),b=plan(a.schedules,data);assert.equal(a.added,1);assert.equal(b.added,0);assert.equal(b.updated,0);assert.equal(b.unchanged,1);assert.deepEqual(b.schedules,a.schedules)});
test('completion, color, project links survive updates',()=>{const data=fixture(),a=plan([],data);Object.assign(a.schedules[0],{done:true,color:'#123456',projectId:'project',nodeId:'node',taskId:'task'});data.events[0].start='08:15';data.events[0].location='教学楼102';const b=plan(a.schedules,data);assert.equal(b.schedules[0].done,true);assert.equal(b.schedules[0].color,'#123456');assert.equal(b.schedules[0].taskId,'task');assert.equal(b.schedules[0].start,'08:15');assert.equal(b.schedules[0].source.location,'教学楼102')});
test('local edits preserved while untouched fields update',()=>{const data=fixture(),a=plan([],data);a.schedules[0].name='私人备注';data.events[0].name='学校新名称';data.events[0].end='09:40';let b=plan(a.schedules,data);assert.equal(b.keptEdits,1);assert.equal(b.schedules[0].name,'私人备注');assert.equal(b.schedules[0].end,'09:40');b=plan(b.schedules,data);assert.equal(b.updated,0);assert.equal(b.schedules[0].name,'私人备注')});
test('manual repeat rule not overwritten',()=>{const data=fixture(),a=plan([],data);a.schedules[0].repeat='daily';a.schedules[0].endDate='2026-10-31';data.events[0].date='2026-10-06';const b=plan(a.schedules,data);assert.equal(b.schedules[0].repeat,'daily');assert.equal(b.schedules[0].date,'2026-10-05');assert.equal(b.schedules[0].endDate,'2026-10-31')});
test('missing courses retained by default and incomplete cannot remove',()=>{const data=fixture(),a=plan([],data);data.events=[];assert.equal(plan(a.schedules,data).schedules[0].source.cancelled,true);data.complete=false;const b=plan(a.schedules,data,{removeMissing:true});assert.equal(b.schedules.length,1);assert.equal(b.cancelled,0);assert.equal(b.schedules[0].source.cancelled,false)});
test('optional removal excludes done, linked and edited schedules',()=>{const data=fixture(),a=plan([],data);data.events=[];assert.equal(plan(a.schedules,data,{removeMissing:true}).removed,1);for(const change of [{done:true},{taskId:'task'},{projectId:'project'},{name:'私人备注'}]){const old=structuredClone(a.schedules);Object.assign(old[0],change);assert.equal(plan(old,data,{removeMissing:true}).removed,0)}});
test('manual events and other semester or account stay untouched',()=>{const data=fixture(),a=plan([],data);a.schedules.push({id:'manual',name:'手动日程'});const other=fixture();other.accountKey='c'.repeat(24);assert.equal(plan(a.schedules,other,{removeMissing:true}).schedules.length,3);other.accountKey=data.accountKey;other.termId='2026-2027-2';assert.equal(plan(a.schedules,other,{removeMissing:true}).schedules.length,3)});
test('cancelled course can return without losing done',()=>{const data=fixture(),a=plan([],data);a.schedules[0].done=true;const missing=fixture();missing.events=[];const b=plan(a.schedules,missing),c=plan(b.schedules,data);assert.equal(c.schedules[0].source.cancelled,false);assert.equal(c.schedules[0].done,true);assert.equal(c.added,0)});
test('input immutable and invalid dates or duplicate IDs rejected',()=>{const data=fixture(),before=JSON.stringify(data);plan([],data);assert.equal(JSON.stringify(data),before);data.events.push({...data.events[0]});assert.throws(()=>validate(data));data.events.pop();data.events[0].date='2026-02-30';assert.throws(()=>validate(data))});
