const test=require('node:test'),assert=require('node:assert/strict');
const api=require('../school-tools');
function event(date='2026-10-02'){return{id:'course',date:date,repeat:'none',done:true,source:{provider:'bupt'}}}
function rule(){return{id:'national',name:'国庆节',enabled:true,start:'2026-10-01',end:'2026-10-07',makeup:false,moves:[]}}
function homework(){return{provider:'bupt-ucloud',accountKey:'a'.repeat(24),fetchedAt:'2026-10-02T00:00:00+08:00',assignments:[{sourceId:'work_123',title:'实验一',courseName:'测试课程',name:'测试课程：实验一',dueAt:'2026-10-10T23:59+08:00'}]}}
test('homework names migrate to course colon title without losing completion or custom edits',()=>{const plan=api.homeworkPlan([],null,homework()),item=plan.inbox[0];item.name='【测试课程】实验一';item.source.snapshotName=item.name;item.done=true;const next=api.normalizeHomeworkItem(item);assert.equal(next.name,'测试课程：实验一');assert.equal(next.source.snapshotName,next.name);assert(next.done);assert.equal(item.name,'【测试课程】实验一');assert.equal(api.normalizeHomeworkItem({...item,name:'我的改名'}).name,'我的改名');assert.equal(api.normalizeHomeworkItem({...item,source:{...item.source,courseName:'',snapshotName:item.name}}).name,'实验一');assert.equal(api.normalizeHomeworkItem({name:'一般事项',done:false}).name,'一般事项')});
test('holiday boundaries inclusive and manual schedules untouched',()=>{const r=rule();for(const date of [r.start,r.end])assert(api.decision(event(date),[r]).hidden);assert(!api.decision(event('2026-09-30'),[r]).hidden);assert(!api.decision({...event(),source:null},[r]).hidden);assert(!api.decision({...event(),repeat:'weekly'},[r]).hidden)});
test('makeup changes display date without mutating original completion or ID',()=>{const r=rule(),e=event();r.makeup=true;r.moves=[{from:e.date,to:'2026-10-10'}];api.validateRules([r]);const d=api.decision(e,[r]);assert(!d.hidden);assert(d.moved);assert.equal(d.date,'2026-10-10');assert.equal(e.date,'2026-10-02');assert(e.done);r.enabled=false;assert.equal(api.decision(e,[r]).date,e.date)});
test('rules persist independently and resync cannot restore suppressed course',()=>{const r=rule();assert.equal(api.impact([event(),event('2026-10-10')],[r]).hidden,1);const reload=JSON.parse(JSON.stringify([r]));assert(api.decision({...event()},api.normalizeRules(reload)).hidden);r.enabled=false;assert(!api.decision(event(),[r]).hidden)});
test('ambiguous or invalid holiday and makeup dates rejected',()=>{assert.throws(()=>api.validateRules([{...rule(),start:'2026-02-30'}]));assert.throws(()=>api.validateRules([rule(),rule()]));assert.throws(()=>api.validateRules([{...rule(),makeup:true,moves:[{from:'2026-10-02',to:'2026-10-03'}]}]));assert.throws(()=>api.validateRules([{...rule(),makeup:true,moves:[{from:'2026-10-02',to:'2026-10-10'},{from:'2026-10-03',to:'2026-10-10'}]}]))});
test('preset has all seven verified festivals and no guessed makeup mappings',()=>{const presets=api.preset2026();assert.equal(presets.length,7);assert.equal(presets[6].start,'2026-10-01');assert(presets.every(r=>r.moves.length===0));assert.equal(api.validateRules(presets).length,7)});
test('homework import idempotent and done state retained',()=>{const data=homework(),a=api.homeworkPlan([],null,data);a.inbox[0].done=true;const b=api.homeworkPlan(a.inbox,a.homeworkSync,data);assert.equal(b.added,0);assert.equal(b.updated,0);assert.equal(b.inbox.length,1);assert(b.inbox[0].done);assert.equal(b.inbox[0].source.dueAt,data.assignments[0].dueAt)});
test('deadline updates and custom names preserved',()=>{const data=homework(),a=api.homeworkPlan([],null,data);a.inbox[0].name='我的改名';data.assignments[0].dueAt='2026-10-12T23:59+08:00';const b=api.homeworkPlan(a.inbox,a.homeworkSync,data);assert.equal(b.updated,1);assert.equal(b.inbox[0].name,'我的改名');assert.equal(b.inbox[0].source.dueAt,data.assignments[0].dueAt)});
test('collected or deleted homework not recreated; other account separate',()=>{const data=homework(),a=api.homeworkPlan([],null,data),b=api.homeworkPlan([],a.homeworkSync,data);assert.equal(b.alreadyCollected,1);assert.equal(b.inbox.length,0);data.accountKey='b'.repeat(24);assert.equal(api.homeworkPlan([],a.homeworkSync,data).added,1)});
test('selective import and platform disappearance never deletes local items',()=>{const data=homework();assert.equal(api.homeworkPlan([],null,data,[]).added,0);const a=api.homeworkPlan([],null,data);data.assignments=[];assert.equal(api.homeworkPlan(a.inbox,a.homeworkSync,data).inbox.length,1)});
test('homework input validation and source allowlist',()=>{const data=homework();data.assignments.push({...data.assignments[0]});assert.throws(()=>api.homeworkPlan([],null,data));data.assignments.pop();const a=api.homeworkPlan([],null,data);assert.equal(api.normalizeHomeworkSource({...a.inbox[0].source,password:'secret'}).password,undefined);assert.equal(api.normalizeHomeworkSource({provider:'unknown'}),null)});
